[package]
name = "markov"
version = "0.1.0"
authors = ["Victor Reyes <vreyes85739@outlook.com>"]
edition = "2018"

[lib]
name = "markov"
path = "src/lib.rs"

[[bin]]
name = "markov"
path = "src/main.rs"

[dependencies]
structopt = "0.3.13"
anyhow = "1.0"
