[package]
name = "markov"
version = "0.1.0"
authors = ["Victor Reyes <vreyes85739@outlook.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.13"
anyhow = "1.0"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
