[package]
name = "vivisix"
version = "0.1.0"
authors = ["Victor Reyes <vreyes85739@outlook.com>"]
edition = "2018"

[lib]
name = "vivisix"
path = "src/lib.rs"

[[bin]]
name = "vivi"
path = "src/main.rs"

[dependencies]
text_io = "0.1.9"