[package]
name = "prim"
version = "0.1.0"
authors = ["Victor Reyes <vreyes85739@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
lazy_static = "1.4.0"
prettytable-rs = "0.8.0"
