[package]
name = "aq"
version = "0.1.0"
authors = ["Victor Reyes <vreyes85739@outlook.com>"]
edition = "2018"

[lib]
name = "libaq"
path = "src/lib.rs"

[[bin]]
name = "aq"
path = "src/main.rs"

[dependencies]
colored = "2"
clap = "~2.27.0"
