[package]
name = "aq"
version = "0.1.0"
authors = ["Victor Reyes <vreyes85739@outlook.com>"]
edition = "2018"

[lib]
name = "aq"
path = "src/lib.rs"

[[bin]]
name = "aqq"
path = "src/main.rs"

[dependencies]
toei = { git = "https://github.com/feydor/toei" }
lazy_static = "1.4.0"
clap = "~2.27.0"
